# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailer_host: <%= ENV['MAILER_HOST'] %>

local: &local
  <<: *common

remote: &remote
  <<: *common
  redis_url: <%= ENV['REDIS_URL'] %>

development:
  <<: *local
  secret_key_base: adfd3f9673cfd43f6f63411c6b3f3300ebee904cc8832298f3df6d37213536284568df0cf5ea4cd63f6c41c7c7c0fe51ad666696467ca1f641aa84313714ff2a
  redis_url: 'redis://localhost:6379'

test:
  <<: *remote
  secret_key_base: b6d08ca98f7f5642873b3cce59dd55b2e877ee6d7412156c095f875eca1ff0fe5de6a81d00fa2bfda2f7a64b6e56fad8a471489824eb31d91548945ce9a3c2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *remote
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>